on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Test and Collect Coverage

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: npm install, make test-coverage
        run: |
          npm install
          npm run test
          npm run collect-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
